/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedServiciosRouteImport } from './routes/_authenticated/servicios'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedLaboratorioRouteImport } from './routes/_authenticated/laboratorio'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedHistoriasRouteImport } from './routes/_authenticated/historias'
import { Route as AuthenticatedFacturacionRouteImport } from './routes/_authenticated/facturacion'
import { Route as AuthenticatedDoctoresRouteImport } from './routes/_authenticated/doctores'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiciosRoute = AuthenticatedServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaboratorioRoute =
  AuthenticatedLaboratorioRouteImport.update({
    id: '/laboratorio',
    path: '/laboratorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriasRoute = AuthenticatedHistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturacionRoute =
  AuthenticatedFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctoresRoute = AuthenticatedDoctoresRouteImport.update({
  id: '/doctores',
  path: '/doctores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/doctores': typeof AuthenticatedDoctoresRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/historias': typeof AuthenticatedHistoriasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/servicios': typeof AuthenticatedServiciosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/doctores': typeof AuthenticatedDoctoresRoute
  '/facturacion': typeof AuthenticatedFacturacionRoute
  '/historias': typeof AuthenticatedHistoriasRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/servicios': typeof AuthenticatedServiciosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/doctores': typeof AuthenticatedDoctoresRoute
  '/_authenticated/facturacion': typeof AuthenticatedFacturacionRoute
  '/_authenticated/historias': typeof AuthenticatedHistoriasRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/laboratorio': typeof AuthenticatedLaboratorioRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/servicios': typeof AuthenticatedServiciosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/configuracion'
    | '/doctores'
    | '/facturacion'
    | '/historias'
    | '/inventario'
    | '/laboratorio'
    | '/pacientes'
    | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agenda'
    | '/configuracion'
    | '/doctores'
    | '/facturacion'
    | '/historias'
    | '/inventario'
    | '/laboratorio'
    | '/pacientes'
    | '/servicios'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracion'
    | '/_authenticated/doctores'
    | '/_authenticated/facturacion'
    | '/_authenticated/historias'
    | '/_authenticated/inventario'
    | '/_authenticated/laboratorio'
    | '/_authenticated/pacientes'
    | '/_authenticated/servicios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicios': {
      id: '/_authenticated/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof AuthenticatedServiciosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laboratorio': {
      id: '/_authenticated/laboratorio'
      path: '/laboratorio'
      fullPath: '/laboratorio'
      preLoaderRoute: typeof AuthenticatedLaboratorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historias': {
      id: '/_authenticated/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof AuthenticatedHistoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion': {
      id: '/_authenticated/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AuthenticatedFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctores': {
      id: '/_authenticated/doctores'
      path: '/doctores'
      fullPath: '/doctores'
      preLoaderRoute: typeof AuthenticatedDoctoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDoctoresRoute: typeof AuthenticatedDoctoresRoute
  AuthenticatedFacturacionRoute: typeof AuthenticatedFacturacionRoute
  AuthenticatedHistoriasRoute: typeof AuthenticatedHistoriasRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedLaboratorioRoute: typeof AuthenticatedLaboratorioRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedServiciosRoute: typeof AuthenticatedServiciosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDoctoresRoute: AuthenticatedDoctoresRoute,
  AuthenticatedFacturacionRoute: AuthenticatedFacturacionRoute,
  AuthenticatedHistoriasRoute: AuthenticatedHistoriasRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedLaboratorioRoute: AuthenticatedLaboratorioRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedServiciosRoute: AuthenticatedServiciosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
