-- COMPLETE DATABASE SCHEMA DUMP
-- Generated by combining all migrations

-- Migration: 20260609051914_87b87a5b-d631-4d15-8afc-cdb40a03d07b.sql

-- ============================================
-- FASE 1: Auth, Roles, Pacientes y Citas
-- ============================================

-- 1. Enum de roles
CREATE TYPE public.app_role AS ENUM ('admin', 'doctor');

-- 2. Tabla profiles (datos públicos del usuario)
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  avatar_url text,
  specialty text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Tabla user_roles (separada para evitar privilege escalation)
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- 4. Función has_role (SECURITY DEFINER para evitar recursión RLS)
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- 5. Función helper: ¿es admin?
CREATE OR REPLACE FUNCTION public.is_admin(_user_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.has_role(_user_id, 'admin'::public.app_role)
$$;

-- 6. Trigger para auto-crear profile en signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email
  );
  -- Default role: doctor (admin debe promoverlos manualmente)
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'doctor'::public.app_role);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. Función updated_at compartida
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

-- 8. Políticas profiles
CREATE POLICY "Users view own profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins view all profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Users view doctors profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.has_role(id, 'doctor'::public.app_role));
CREATE POLICY "Users update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins update any profile" ON public.profiles
  FOR UPDATE TO authenticated USING (public.is_admin(auth.uid()));

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 9. Políticas user_roles
CREATE POLICY "Users view own roles" ON public.user_roles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins view all roles" ON public.user_roles
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins manage roles" ON public.user_roles
  FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

-- 10. Tabla patients
CREATE TABLE public.patients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text,
  phone text,
  birth_date date,
  gender text,
  address text,
  status text NOT NULL DEFAULT 'activo',
  assigned_doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.patients TO authenticated;
GRANT ALL ON public.patients TO service_role;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all patients" ON public.patients
  FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors view assigned patients" ON public.patients
  FOR SELECT TO authenticated
  USING (assigned_doctor_id = auth.uid());
CREATE POLICY "Doctors insert patients" ON public.patients
  FOR INSERT TO authenticated
  WITH CHECK (
    public.has_role(auth.uid(), 'doctor'::public.app_role)
    AND assigned_doctor_id = auth.uid()
  );
CREATE POLICY "Doctors update assigned patients" ON public.patients
  FOR UPDATE TO authenticated
  USING (assigned_doctor_id = auth.uid())
  WITH CHECK (assigned_doctor_id = auth.uid());
CREATE POLICY "Doctors delete assigned patients" ON public.patients
  FOR DELETE TO authenticated
  USING (assigned_doctor_id = auth.uid());

CREATE TRIGGER patients_updated_at BEFORE UPDATE ON public.patients
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_patients_assigned_doctor ON public.patients(assigned_doctor_id);
CREATE INDEX idx_patients_status ON public.patients(status);

-- 11. Tabla appointments
CREATE TABLE public.appointments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scheduled_at timestamptz NOT NULL,
  duration_minutes int NOT NULL DEFAULT 30,
  status text NOT NULL DEFAULT 'programada',
  reason text,
  notes text,
  price numeric(10,2) DEFAULT 0,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.appointments TO authenticated;
GRANT ALL ON public.appointments TO service_role;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all appointments" ON public.appointments
  FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors view own appointments" ON public.appointments
  FOR SELECT TO authenticated USING (doctor_id = auth.uid());
CREATE POLICY "Doctors insert own appointments" ON public.appointments
  FOR INSERT TO authenticated WITH CHECK (doctor_id = auth.uid());
CREATE POLICY "Doctors update own appointments" ON public.appointments
  FOR UPDATE TO authenticated
  USING (doctor_id = auth.uid()) WITH CHECK (doctor_id = auth.uid());
CREATE POLICY "Doctors delete own appointments" ON public.appointments
  FOR DELETE TO authenticated USING (doctor_id = auth.uid());

CREATE TRIGGER appointments_updated_at BEFORE UPDATE ON public.appointments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX idx_appointments_patient ON public.appointments(patient_id);
CREATE INDEX idx_appointments_scheduled ON public.appointments(scheduled_at);
CREATE INDEX idx_appointments_status ON public.appointments(status);


-- Migration: 20260609051935_f953c488-4806-48d8-bfc6-8aa1ba46a177.sql

-- Revocar execute público de funciones que NO deben llamarse desde la API
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;

-- has_role / is_admin: necesarias para policies. Restringir a authenticated only.
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;


-- Migration: 20260609052610_3c1bdd85-b95a-4675-9ea5-5e4aaf5a77df.sql

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_count int;
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email
  );
  -- Bootstrap: el primer usuario registrado se vuelve admin automáticamente
  SELECT count(*) INTO user_count FROM public.profiles;
  IF user_count <= 1 THEN
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin'::public.app_role);
  ELSE
    INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'doctor'::public.app_role);
  END IF;
  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;


-- Migration: 20260610040631_32def3a5-fb65-4db2-b035-c9f59de81b58.sql

-- clinical_notes
CREATE TABLE public.clinical_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  note_date timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.clinical_notes TO authenticated;
GRANT ALL ON public.clinical_notes TO service_role;

ALTER TABLE public.clinical_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all clinical notes"
  ON public.clinical_notes FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Doctors manage notes of their patients"
  ON public.clinical_notes FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.patients p
      WHERE p.id = patient_id AND p.assigned_doctor_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.patients p
      WHERE p.id = patient_id AND p.assigned_doctor_id = auth.uid()
    )
  );

CREATE INDEX idx_clinical_notes_patient ON public.clinical_notes(patient_id, note_date DESC);

CREATE TRIGGER trg_clinical_notes_updated_at
  BEFORE UPDATE ON public.clinical_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- lab_results
CREATE TABLE public.lab_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  test_type text NOT NULL,
  result text,
  status text NOT NULL DEFAULT 'pendiente',
  file_url text,
  result_date timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_results TO authenticated;
GRANT ALL ON public.lab_results TO service_role;

ALTER TABLE public.lab_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all lab results"
  ON public.lab_results FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Doctors manage lab results of their appointments"
  ON public.lab_results FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.appointments a
      WHERE a.id = appointment_id AND a.doctor_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.appointments a
      WHERE a.id = appointment_id AND a.doctor_id = auth.uid()
    )
  );

CREATE INDEX idx_lab_results_appointment ON public.lab_results(appointment_id);
CREATE INDEX idx_lab_results_patient ON public.lab_results(patient_id, created_at DESC);

CREATE TRIGGER trg_lab_results_updated_at
  BEFORE UPDATE ON public.lab_results
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Migration: 20260610223700_add_document_id_to_patients.sql
-- Add document_id column to public.patients table
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS document_id text;


-- Migration: 20260610231200_drop_gender_from_patients.sql
-- Drop gender column from public.patients table
ALTER TABLE public.patients DROP COLUMN IF EXISTS gender;


-- Migration: 20260611010000_extend_schema_femesalud.sql
-- Extended clinical schema for FemeSalud

-- 1. Create enum for visit type
CREATE TYPE public.visit_type_enum AS ENUM ('CONTROL', 'EMERGENCIA', 'CONSULTA_NUEVA', 'POST_TRATAMIENTO', 'OTRO');

-- 2. Create sequence for historia_number
CREATE SEQUENCE IF NOT EXISTS public.historia_number_seq START WITH 3000;

-- 3. Extend patients table
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS historia_number text UNIQUE DEFAULT nextval('public.historia_number_seq')::text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS first_visit_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS marital_status text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS birthplace text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS education_level text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS occupation text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS ethnicity text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS family_history jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS personal_history jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS gynecological_data jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS obstetric_data jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS consultation_reason text;
ALTER TABLE public.patients ADD COLUMN IF NOT EXISTS current_illness text;

-- 4. Create consultations table
CREATE TABLE public.consultations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  
  -- General info
  visit_type public.visit_type_enum NOT NULL DEFAULT 'CONTROL',
  is_first_visit boolean NOT NULL DEFAULT false,
  subjective_exam text,
  
  -- Vitals
  height_cm numeric(5,1),
  weight_kg numeric(5,1),
  bmi numeric(5,1),
  blood_pressure text,
  heart_rate integer,
  respiratory_rate integer,
  temperature numeric(4,1),
  
  -- Physical exam / review of systems
  skin text,
  head_neck text,
  breasts text,
  abdomen text,
  gynecological text,
  extremities text,
  neurological text,
  
  -- Colposcopy
  acetic_acid_test text,
  acetic_clock_position text,
  acetic_relative_position text,
  lugol_test text,
  lugol_clock_position text,
  lugol_relative_position text,
  
  -- Obstetrics (conditional)
  gestational_age text,
  fetal_weight numeric(7,1),
  obstetric_bp text,
  uterine_height numeric(5,1),
  presentation text,
  fetal_heart_rate integer,
  fetal_movements text,
  edema text,
  alarm_signs text,
  
  -- Plan / Treatment
  indications text,
  complementary_exams text,
  diagnosis text,
  plan text,
  next_appointment_date date,
  
  -- Marketing
  contact_channel text,
  
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- RLS & Grants for consultations
GRANT SELECT, INSERT, UPDATE, DELETE ON public.consultations TO authenticated;
GRANT ALL ON public.consultations TO service_role;

ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all consultations"
  ON public.consultations FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Doctors manage consultations of their appointments"
  ON public.consultations FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.appointments a
      WHERE a.id = appointment_id AND a.doctor_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.appointments a
      WHERE a.id = appointment_id AND a.doctor_id = auth.uid()
    )
  );

CREATE TRIGGER trg_consultations_updated_at
  BEFORE UPDATE ON public.consultations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 5. Create consultation_consumables table
CREATE TABLE public.consultation_consumables (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE,
  item_name text NOT NULL,
  quantity numeric(10,2) NOT NULL DEFAULT 0.0,
  unit text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS & Grants for consultation_consumables
GRANT SELECT, INSERT, UPDATE, DELETE ON public.consultation_consumables TO authenticated;
GRANT ALL ON public.consultation_consumables TO service_role;

ALTER TABLE public.consultation_consumables ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins manage all consultation consumables"
  ON public.consultation_consumables FOR ALL
  TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE POLICY "Doctors manage consumables of their consultations"
  ON public.consultation_consumables FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.consultations c
      JOIN public.appointments a ON a.id = c.appointment_id
      WHERE c.id = consultation_id AND a.doctor_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.consultations c
      JOIN public.appointments a ON a.id = c.appointment_id
      WHERE c.id = consultation_id AND a.doctor_id = auth.uid()
    )
  );


-- Migration: 20260611034600_complete_schema.sql

-- profiles (User profiles linked to auth.users)
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  avatar_url text,
  specialty text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- user_roles (Roles assigned to users)
CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

-- patients (Patient clinical registries)
CREATE TABLE public.patients (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text,
  phone text,
  birth_date date,
  address text,
  status text NOT NULL DEFAULT 'activo',
  assigned_doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  document_id text,
  historia_number text UNIQUE DEFAULT nextval('public.historia_number_seq')::text,
  first_visit_date date DEFAULT CURRENT_DATE,
  marital_status text,
  birthplace text,
  education_level text,
  occupation text,
  ethnicity text,
  family_history jsonb DEFAULT '{}'::jsonb,
  personal_history jsonb DEFAULT '{}'::jsonb,
  gynecological_data jsonb DEFAULT '{}'::jsonb,
  obstetric_data jsonb DEFAULT '{}'::jsonb,
  consultation_reason text,
  current_illness text
);

-- appointments (Agendación de citas)
CREATE TABLE public.appointments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  scheduled_at timestamptz NOT NULL,
  duration_minutes int NOT NULL DEFAULT 30,
  status text NOT NULL DEFAULT 'programada',
  reason text,
  notes text,
  price numeric(10,2) DEFAULT 0,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- clinical_notes (Notas clínicas libres)
CREATE TABLE public.clinical_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  author_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  title text NOT NULL,
  content text NOT NULL DEFAULT '',
  note_date timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- lab_results (Resultados de laboratorio)
CREATE TABLE public.lab_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  test_type text NOT NULL,
  result text,
  status text NOT NULL DEFAULT 'pendiente',
  file_url text,
  result_date timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- consultations (Consultas médicas estructuradas)
CREATE TABLE public.consultations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id uuid NOT NULL REFERENCES public.appointments(id) ON DELETE CASCADE,
  patient_id uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  doctor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  visit_type public.visit_type_enum NOT NULL DEFAULT 'CONTROL',
  is_first_visit boolean NOT NULL DEFAULT false,
  subjective_exam text,
  height_cm numeric(5,1),
  weight_kg numeric(5,1),
  bmi numeric(5,1),
  blood_pressure text,
  heart_rate integer,
  respiratory_rate integer,
  temperature numeric(4,1),
  skin text,
  head_neck text,
  breasts text,
  abdomen text,
  gynecological text,
  extremities text,
  neurological text,
  acetic_acid_test text,
  acetic_clock_position text,
  acetic_relative_position text,
  lugol_test text,
  lugol_clock_position text,
  lugol_relative_position text,
  gestational_age text,
  fetal_weight numeric(7,1),
  obstetric_bp text,
  uterine_height numeric(5,1),
  presentation text,
  fetal_heart_rate integer,
  fetal_movements text,
  edema text,
  alarm_signs text,
  indications text,
  complementary_exams text,
  diagnosis text,
  plan text,
  next_appointment_date date,
  contact_channel text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- consultation_consumables (Materiales consumidos en la consulta)
CREATE TABLE public.consultation_consumables (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL REFERENCES public.consultations(id) ON DELETE CASCADE,
  item_name text NOT NULL,
  quantity numeric(10,2) NOT NULL DEFAULT 0.0,
  unit text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. DATABASE FUNCTIONS AND PROCEDURES

-- has_role (Security Definer helper to check roles)
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- is_admin (Security Definer helper to check admin role)
CREATE OR REPLACE FUNCTION public.is_admin(_user_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.has_role(_user_id, 'admin'::public.app_role)
$$;

-- set_updated_at (Trigger function to automatically update updated_at columns)
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

-- handle_new_user (Auto-creation of profiles and admin role assignment for testing)
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email
  ) ON CONFLICT (id) DO NOTHING;
  
  -- Assign admin role to all registered users for testing and deployment ease
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'admin'::public.app_role)
  ON CONFLICT (user_id, role) DO NOTHING;
  
  RETURN NEW;
END;
$function$;

-- 5. FUNCTION SECURITY AND PERMISSIONS
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;

-- 6. TRIGGERS CREATION
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER patients_updated_at BEFORE UPDATE ON public.patients
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER appointments_updated_at BEFORE UPDATE ON public.appointments
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_clinical_notes_updated_at BEFORE UPDATE ON public.clinical_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_lab_results_updated_at BEFORE UPDATE ON public.lab_results
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_consultations_updated_at BEFORE UPDATE ON public.consultations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 7. ROLES GRANTS
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;

GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.patients TO authenticated;
GRANT ALL ON public.patients TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.appointments TO authenticated;
GRANT ALL ON public.appointments TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.clinical_notes TO authenticated;
GRANT ALL ON public.clinical_notes TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.lab_results TO authenticated;
GRANT ALL ON public.lab_results TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.consultations TO authenticated;
GRANT ALL ON public.consultations TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.consultation_consumables TO authenticated;
GRANT ALL ON public.consultation_consumables TO service_role;

-- 8. ROW LEVEL SECURITY (RLS) ACTIVATION
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinical_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lab_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.consultation_consumables ENABLE ROW LEVEL SECURITY;

-- 9. SECURITY POLICIES

-- profiles
CREATE POLICY "Users view own profile" ON public.profiles
  FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins view all profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Users view doctors profiles" ON public.profiles
  FOR SELECT TO authenticated USING (public.has_role(id, 'doctor'::public.app_role));
CREATE POLICY "Users update own profile" ON public.profiles
  FOR UPDATE TO authenticated USING (auth.uid() = id);
CREATE POLICY "Admins update any profile" ON public.profiles
  FOR UPDATE TO authenticated USING (public.is_admin(auth.uid()));

-- user_roles
CREATE POLICY "Users view own roles" ON public.user_roles
  FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Admins view all roles" ON public.user_roles
  FOR SELECT TO authenticated USING (public.is_admin(auth.uid()));
CREATE POLICY "Admins manage roles" ON public.user_roles
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- patients
CREATE POLICY "Admins manage all patients" ON public.patients
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors view assigned patients" ON public.patients
  FOR SELECT TO authenticated USING (assigned_doctor_id = auth.uid());
CREATE POLICY "Doctors insert patients" ON public.patients
  FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(), 'doctor'::public.app_role) AND assigned_doctor_id = auth.uid());
CREATE POLICY "Doctors update assigned patients" ON public.patients
  FOR UPDATE TO authenticated USING (assigned_doctor_id = auth.uid()) WITH CHECK (assigned_doctor_id = auth.uid());
CREATE POLICY "Doctors delete assigned patients" ON public.patients
  FOR DELETE TO authenticated USING (assigned_doctor_id = auth.uid());

-- appointments
CREATE POLICY "Admins manage all appointments" ON public.appointments
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors view own appointments" ON public.appointments
  FOR SELECT TO authenticated USING (doctor_id = auth.uid());
CREATE POLICY "Doctors insert own appointments" ON public.appointments
  FOR INSERT TO authenticated WITH CHECK (doctor_id = auth.uid());
CREATE POLICY "Doctors update own appointments" ON public.appointments
  FOR UPDATE TO authenticated USING (doctor_id = auth.uid()) WITH CHECK (doctor_id = auth.uid());
CREATE POLICY "Doctors delete own appointments" ON public.appointments
  FOR DELETE TO authenticated USING (doctor_id = auth.uid());

-- clinical_notes
CREATE POLICY "Admins manage all clinical notes" ON public.clinical_notes
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors manage notes of their patients" ON public.clinical_notes
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.assigned_doctor_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.patients p WHERE p.id = patient_id AND p.assigned_doctor_id = auth.uid()));

-- lab_results
CREATE POLICY "Admins manage all lab results" ON public.lab_results
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors manage lab results of their appointments" ON public.lab_results
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.appointments a WHERE a.id = appointment_id AND a.doctor_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.appointments a WHERE a.id = appointment_id AND a.doctor_id = auth.uid()));

-- consultations
CREATE POLICY "Admins manage all consultations" ON public.consultations
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors manage consultations of their appointments" ON public.consultations
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.appointments a WHERE a.id = appointment_id AND a.doctor_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.appointments a WHERE a.id = appointment_id AND a.doctor_id = auth.uid()));

-- consultation_consumables
CREATE POLICY "Admins manage all consultation consumables" ON public.consultation_consumables
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));
CREATE POLICY "Doctors manage consumables of their consultations" ON public.consultation_consumables
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.consultations c JOIN public.appointments a ON a.id = c.appointment_id WHERE c.id = consultation_id AND a.doctor_id = auth.uid()))
  WITH CHECK (EXISTS (SELECT 1 FROM public.consultations c JOIN public.appointments a ON a.id = c.appointment_id WHERE c.id = consultation_id AND a.doctor_id = auth.uid()));

-- 10. INDEXES CREATION
CREATE INDEX idx_patients_assigned_doctor ON public.patients(assigned_doctor_id);
CREATE INDEX idx_patients_status ON public.patients(status);

CREATE INDEX idx_appointments_doctor ON public.appointments(doctor_id);
CREATE INDEX idx_appointments_patient ON public.appointments(patient_id);
CREATE INDEX idx_appointments_scheduled ON public.appointments(scheduled_at);
CREATE INDEX idx_appointments_status ON public.appointments(status);

CREATE INDEX idx_clinical_notes_patient ON public.clinical_notes(patient_id, note_date DESC);

CREATE INDEX idx_lab_results_appointment ON public.lab_results(appointment_id);
CREATE INDEX idx_lab_results_patient ON public.lab_results(patient_id, created_at DESC);

-- 11. INITIAL SEEDING FOR MOCK ADMIN/DOCTOR USER
-- Seeding default user auth
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, aud, role)
VALUES (
  'e0000000-0000-0000-0000-000000000001',
  'doctor@femesalud.example.com',
  crypt('password123', gen_salt('bf', 10)),
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{"full_name":"Dra. Carli Solé Aquino"}'::jsonb,
  'authenticated',
  'authenticated'
) ON CONFLICT (id) DO NOTHING;

-- Seeding profile
INSERT INTO public.profiles (id, full_name, email, specialty)
VALUES (
  'e0000000-0000-0000-0000-000000000001',
  'Dra. Carli Solé Aquino',
  'doctor@femesalud.example.com',
  'Ginecología y Obstetricia'
) ON CONFLICT (id) DO UPDATE SET specialty = 'Ginecología y Obstetricia';

-- Seeding admin user_role
INSERT INTO public.user_roles (user_id, role)
VALUES (
  'e0000000-0000-0000-0000-000000000001',
  'admin'::public.app_role
) ON CONFLICT (user_id, role) DO NOTHING;


-- Migration: 20260611042119_74b084ee-0e4a-4016-8cf6-c294bac688a2.sql

ALTER TABLE public.clinical_notes
  ADD COLUMN IF NOT EXISTS attachments jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Storage policies for the 'clinical-attachments' bucket.
-- Path convention: <patient_id>/<filename-or-subpath>
CREATE POLICY "clinical_attachments_admin_all"
ON storage.objects FOR ALL TO authenticated
USING (bucket_id = 'clinical-attachments' AND public.is_admin(auth.uid()))
WITH CHECK (bucket_id = 'clinical-attachments' AND public.is_admin(auth.uid()));

CREATE POLICY "clinical_attachments_doctor_select"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'clinical-attachments'
  AND EXISTS (
    SELECT 1 FROM public.patients p
    WHERE p.id::text = (storage.foldername(name))[1]
      AND p.assigned_doctor_id = auth.uid()
  )
);

CREATE POLICY "clinical_attachments_doctor_insert"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'clinical-attachments'
  AND EXISTS (
    SELECT 1 FROM public.patients p
    WHERE p.id::text = (storage.foldername(name))[1]
      AND p.assigned_doctor_id = auth.uid()
  )
);

CREATE POLICY "clinical_attachments_doctor_update"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'clinical-attachments'
  AND EXISTS (
    SELECT 1 FROM public.patients p
    WHERE p.id::text = (storage.foldername(name))[1]
      AND p.assigned_doctor_id = auth.uid()
  )
);

CREATE POLICY "clinical_attachments_doctor_delete"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'clinical-attachments'
  AND EXISTS (
    SELECT 1 FROM public.patients p
    WHERE p.id::text = (storage.foldername(name))[1]
      AND p.assigned_doctor_id = auth.uid()
  )
);


-- Migration: 20260616140000_prescription_templates.sql
CREATE TABLE public.prescription_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    indications TEXT NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.prescription_templates ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to select templates
CREATE POLICY "Doctores y admins pueden ver plantillas" ON public.prescription_templates
    FOR SELECT TO authenticated USING (true);

-- Create policy for authenticated users to insert their templates
CREATE POLICY "Usuarios autenticados pueden crear sus plantillas" ON public.prescription_templates
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = created_by);

-- Create policy for authenticated users to update their templates
CREATE POLICY "Usuarios autenticados pueden actualizar sus plantillas" ON public.prescription_templates
    FOR UPDATE TO authenticated USING (auth.uid() = created_by);

-- Create policy for authenticated users to delete their templates
CREATE POLICY "Usuarios autenticados pueden eliminar sus plantillas" ON public.prescription_templates
    FOR DELETE TO authenticated USING (auth.uid() = created_by);

-- Create trigger to set updated_at
CREATE OR REPLACE FUNCTION public.handle_prescription_templates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_prescription_templates_updated_at
    BEFORE UPDATE ON public.prescription_templates
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_prescription_templates_updated_at();


-- Migration: 20260616190000_enable_realtime.sql
-- Enable Realtime for core tables by adding them to the supabase_realtime publication
do $$
begin
  -- Add public.patients
  if not exists (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'patients'
  ) then
    alter publication supabase_realtime add table public.patients;
  end if;

  -- Add public.appointments
  if not exists (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'appointments'
  ) then
    alter publication supabase_realtime add table public.appointments;
  end if;

  -- Add public.clinical_notes
  if not exists (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'clinical_notes'
  ) then
    alter publication supabase_realtime add table public.clinical_notes;
  end if;

  -- Add public.consultations
  if not exists (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'consultations'
  ) then
    alter publication supabase_realtime add table public.consultations;
  end if;

  -- Add public.prescription_templates
  if not exists (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'prescription_templates'
  ) then
    alter publication supabase_realtime add table public.prescription_templates;
  end if;
end $$;


-- Migration: 20260616200000_create_clinical_attachments_bucket.sql
-- Create the private bucket for clinical attachments
insert into storage.buckets (id, name, public)
values ('clinical-attachments', 'clinical-attachments', false)
on conflict (id) do nothing;

-- Set up policies for the bucket objects
create policy "Authenticated users can upload clinical attachments"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'clinical-attachments'
);

create policy "Authenticated users can view clinical attachments"
on storage.objects for select
to authenticated
using (
  bucket_id = 'clinical-attachments'
);

create policy "Authenticated users can delete clinical attachments"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'clinical-attachments'
);


-- Migration: 20260616210000_add_attachments_to_clinical_notes.sql
-- Add attachments column to public.clinical_notes if it doesn't exist
ALTER TABLE public.clinical_notes
  ADD COLUMN IF NOT EXISTS attachments jsonb NOT NULL DEFAULT '[]'::jsonb;


-- Migration: 20260616220000_cancel_overdue_appointments.sql
-- Auto-cancel appointments that are overdue by more than 15 minutes

-- 1. Try to enable the pg_cron extension safely
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'pg_cron') THEN
    CREATE EXTENSION IF NOT EXISTS pg_cron;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE 'Could not install pg_cron extension: %', SQLERRM;
END;
$$;

-- 2. Create the function to cancel overdue appointments
CREATE OR REPLACE FUNCTION public.cancel_overdue_appointments()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.appointments
  SET status = 'cancelada',
      updated_at = now()
  WHERE status = 'programada'
    AND scheduled_at < (now() - interval '15 minutes');
END;
$$;

-- 3. Schedule the cron job if pg_cron is available
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    -- Unscheduling existing job if it exists to prevent duplicate schedules
    PERFORM cron.unschedule('cancel-overdue-appointments');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'cron') THEN
    PERFORM cron.schedule('cancel-overdue-appointments', '*/1 * * * *', 'SELECT public.cancel_overdue_appointments()');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE 'Could not schedule pg_cron job: %', SQLERRM;
END;
$$;


-- Migration: 20260623162000_phase0_phase1.sql
-- Phase 0 & Phase 1 Optimizations Migration

-- 1. Correct handle_new_user() function
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    NEW.email
  ) ON CONFLICT (id) DO NOTHING;
  
  -- Assign admin role to the first user, and doctor to subsequent users
  IF (SELECT count(*) FROM public.user_roles WHERE role = 'admin') = 0 THEN
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'admin'::public.app_role)
    ON CONFLICT (user_id, role) DO NOTHING;
  ELSE
    INSERT INTO public.user_roles (user_id, role)
    VALUES (NEW.id, 'doctor'::public.app_role)
    ON CONFLICT (user_id, role) DO NOTHING;
  END IF;
  
  RETURN NEW;
END;
$function$;

-- 2. Drop permissive storage policies
DROP POLICY IF EXISTS "Authenticated users can upload clinical attachments" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can view clinical attachments" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete clinical attachments" ON storage.objects;

-- 3. Assert restrictive storage policies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'clinical_attachments_admin_all'
  ) THEN
    CREATE POLICY "clinical_attachments_admin_all"
    ON storage.objects FOR ALL TO authenticated
    USING (bucket_id = 'clinical-attachments' AND public.is_admin(auth.uid()))
    WITH CHECK (bucket_id = 'clinical-attachments' AND public.is_admin(auth.uid()));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'clinical_attachments_doctor_select'
  ) THEN
    CREATE POLICY "clinical_attachments_doctor_select"
    ON storage.objects FOR SELECT TO authenticated
    USING (
      bucket_id = 'clinical-attachments'
      AND EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id::text = (storage.foldername(name))[1]
        AND p.assigned_doctor_id = auth.uid()
      )
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'clinical_attachments_doctor_insert'
  ) THEN
    CREATE POLICY "clinical_attachments_doctor_insert"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (
      bucket_id = 'clinical-attachments'
      AND EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id::text = (storage.foldername(name))[1]
        AND p.assigned_doctor_id = auth.uid()
      )
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'clinical_attachments_doctor_update'
  ) THEN
    CREATE POLICY "clinical_attachments_doctor_update"
    ON storage.objects FOR UPDATE TO authenticated
    USING (
      bucket_id = 'clinical-attachments'
      AND EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id::text = (storage.foldername(name))[1]
        AND p.assigned_doctor_id = auth.uid()
      )
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' AND policyname = 'clinical_attachments_doctor_delete'
  ) THEN
    CREATE POLICY "clinical_attachments_doctor_delete"
    ON storage.objects FOR DELETE TO authenticated
    USING (
      bucket_id = 'clinical-attachments'
      AND EXISTS (
        SELECT 1 FROM public.patients p
        WHERE p.id::text = (storage.foldername(name))[1]
        AND p.assigned_doctor_id = auth.uid()
      )
    );
  END IF;
END $$;

-- 4. Create clinic_info table
CREATE TABLE IF NOT EXISTS public.clinic_info (
  id integer PRIMARY KEY,
  name text NOT NULL,
  address_line1 text NOT NULL,
  address_line2 text NOT NULL,
  phone text NOT NULL,
  rif text NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS on clinic_info
ALTER TABLE public.clinic_info ENABLE ROW LEVEL SECURITY;

-- Create policies for clinic_info
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'clinic_info' AND schemaname = 'public' AND policyname = 'Anyone authenticated can read clinic info'
  ) THEN
    CREATE POLICY "Anyone authenticated can read clinic info"
    ON public.clinic_info FOR SELECT TO authenticated
    USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'clinic_info' AND schemaname = 'public' AND policyname = 'Only admins can update clinic info'
  ) THEN
    CREATE POLICY "Only admins can update clinic info"
    ON public.clinic_info FOR UPDATE TO authenticated
    USING (public.is_admin(auth.uid()));
  END IF;
END $$;

-- Populate clinic_info with default row if it's empty
INSERT INTO public.clinic_info (id, name, address_line1, address_line2, phone, rif, updated_at)
VALUES (
  1,
  'Femesalud',
  'Calle las Flores entre González Padrón y Shettino, Número 16.',
  'Valle de la Pascua, Estado Guárico.',
  '0412/8299890 0424/4609387',
  'J-12345678-9',
  now()
)
ON CONFLICT (id) DO NOTHING;

-- 5. Create Missing Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_consultations_appointment ON public.consultations(appointment_id);
CREATE INDEX IF NOT EXISTS idx_consultations_patient ON public.consultations(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consultations_created ON public.consultations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consultations_doctor ON public.consultations(doctor_id);

CREATE INDEX IF NOT EXISTS idx_consumables_consultation ON public.consultation_consumables(consultation_id);

CREATE INDEX IF NOT EXISTS idx_appointments_status_scheduled ON public.appointments(status, scheduled_at);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_patients_fullname_trgm ON public.patients USING gin(full_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_patients_created ON public.patients(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_templates_created_by ON public.prescription_templates(created_by);


-- Migration: 20260628114200_phase3_atomic_rpcs.sql
-- Phase 3: Atomic RPCs for Consultations

-- 1. Create Consultation RPC
CREATE OR REPLACE FUNCTION create_consultation_rpc(
  p_consultation jsonb,
  p_consumables jsonb DEFAULT '[]'::jsonb
) RETURNS jsonb AS $$
DECLARE
  v_consultation consultations;
  v_orig_app appointments;
  v_user_id uuid;
  v_next_app_date date;
  v_scheduled_at timestamptz;
  v_consumable jsonb;
BEGIN
  v_user_id := auth.uid();
  
  -- Insert consultation
  INSERT INTO consultations (
    appointment_id, patient_id, doctor_id, visit_type, is_first_visit,
    subjective_exam, height_cm, weight_kg, bmi, blood_pressure, heart_rate,
    respiratory_rate, temperature, skin, head_neck, breasts, abdomen,
    gynecological, extremities, neurological, acetic_acid_test, acetic_clock_position,
    acetic_relative_position, lugol_test, lugol_clock_position, lugol_relative_position,
    gestational_age, fetal_weight, obstetric_bp, uterine_height, presentation,
    fetal_heart_rate, fetal_movements, edema, alarm_signs, indications,
    complementary_exams, diagnosis, plan, next_appointment_date, contact_channel
  )
  SELECT 
    (p_consultation->>'appointment_id')::uuid,
    (p_consultation->>'patient_id')::uuid,
    COALESCE((p_consultation->>'doctor_id')::uuid, v_user_id),
    (p_consultation->>'visit_type')::visit_type_enum,
    (p_consultation->>'is_first_visit')::boolean,
    p_consultation->>'subjective_exam',
    (p_consultation->>'height_cm')::numeric,
    (p_consultation->>'weight_kg')::numeric,
    (p_consultation->>'bmi')::numeric,
    p_consultation->>'blood_pressure',
    (p_consultation->>'heart_rate')::integer,
    (p_consultation->>'respiratory_rate')::integer,
    (p_consultation->>'temperature')::numeric,
    p_consultation->>'skin',
    p_consultation->>'head_neck',
    p_consultation->>'breasts',
    p_consultation->>'abdomen',
    p_consultation->>'gynecological',
    p_consultation->>'extremities',
    p_consultation->>'neurological',
    p_consultation->>'acetic_acid_test',
    p_consultation->>'acetic_clock_position',
    p_consultation->>'acetic_relative_position',
    p_consultation->>'lugol_test',
    p_consultation->>'lugol_clock_position',
    p_consultation->>'lugol_relative_position',
    p_consultation->>'gestational_age',
    (p_consultation->>'fetal_weight')::numeric,
    p_consultation->>'obstetric_bp',
    (p_consultation->>'uterine_height')::numeric,
    p_consultation->>'presentation',
    (p_consultation->>'fetal_heart_rate')::integer,
    p_consultation->>'fetal_movements',
    p_consultation->>'edema',
    p_consultation->>'alarm_signs',
    p_consultation->>'indications',
    p_consultation->>'complementary_exams',
    p_consultation->>'diagnosis',
    p_consultation->>'plan',
    (p_consultation->>'next_appointment_date')::date,
    p_consultation->>'contact_channel'
  RETURNING * INTO v_consultation;

  -- Insert consumables if array is not empty
  IF jsonb_array_length(p_consumables) > 0 THEN
    FOR v_consumable IN SELECT * FROM jsonb_array_elements(p_consumables)
    LOOP
      INSERT INTO consultation_consumables (consultation_id, item_name, quantity, unit)
      VALUES (
        v_consultation.id,
        v_consumable->>'item_name',
        (v_consumable->>'quantity')::numeric,
        v_consumable->>'unit'
      );
    END LOOP;
  END IF;

  -- Update appointment status
  UPDATE appointments 
  SET status = 'completada' 
  WHERE id = (p_consultation->>'appointment_id')::uuid;

  -- Create next appointment if next_appointment_date is provided
  IF (p_consultation->>'next_appointment_date') IS NOT NULL THEN
    v_next_app_date := (p_consultation->>'next_appointment_date')::date;
    SELECT * INTO v_orig_app FROM appointments WHERE id = (p_consultation->>'appointment_id')::uuid;
    
    -- Extract time from original appointment and combine with new date
    v_scheduled_at := v_next_app_date + (v_orig_app.scheduled_at::time);
    IF v_scheduled_at IS NULL THEN
      v_scheduled_at := v_next_app_date + time '09:00:00';
    END IF;

    INSERT INTO appointments (
      patient_id, doctor_id, scheduled_at, status, reason, price, created_by
    ) VALUES (
      (p_consultation->>'patient_id')::uuid,
      COALESCE(v_orig_app.doctor_id, (p_consultation->>'doctor_id')::uuid, v_user_id),
      v_scheduled_at,
      'programada',
      'Próxima Cita',
      COALESCE(v_orig_app.price, 0),
      v_user_id
    );
  END IF;

  RETURN to_jsonb(v_consultation);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. Update Consultation RPC
CREATE OR REPLACE FUNCTION update_consultation_rpc(
  p_consultation_id uuid,
  p_patch jsonb,
  p_consumables jsonb DEFAULT NULL
) RETURNS jsonb AS $$
DECLARE
  v_consultation consultations;
  v_old_next_date text;
  v_new_next_date text;
  v_orig_app appointments;
  v_existing_next_app appointments;
  v_user_id uuid;
  v_scheduled_at timestamptz;
  v_consumable jsonb;
BEGIN
  v_user_id := auth.uid();

  -- Get old next_appointment_date
  SELECT next_appointment_date INTO v_old_next_date FROM consultations WHERE id = p_consultation_id;
  
  UPDATE consultations SET
    visit_type = COALESCE((p_patch->>'visit_type')::visit_type_enum, visit_type),
    is_first_visit = COALESCE((p_patch->>'is_first_visit')::boolean, is_first_visit),
    subjective_exam = COALESCE(p_patch->>'subjective_exam', subjective_exam),
    height_cm = COALESCE((p_patch->>'height_cm')::numeric, height_cm),
    weight_kg = COALESCE((p_patch->>'weight_kg')::numeric, weight_kg),
    bmi = COALESCE((p_patch->>'bmi')::numeric, bmi),
    blood_pressure = COALESCE(p_patch->>'blood_pressure', blood_pressure),
    heart_rate = COALESCE((p_patch->>'heart_rate')::integer, heart_rate),
    respiratory_rate = COALESCE((p_patch->>'respiratory_rate')::integer, respiratory_rate),
    temperature = COALESCE((p_patch->>'temperature')::numeric, temperature),
    skin = COALESCE(p_patch->>'skin', skin),
    head_neck = COALESCE(p_patch->>'head_neck', head_neck),
    breasts = COALESCE(p_patch->>'breasts', breasts),
    abdomen = COALESCE(p_patch->>'abdomen', abdomen),
    gynecological = COALESCE(p_patch->>'gynecological', gynecological),
    extremities = COALESCE(p_patch->>'extremities', extremities),
    neurological = COALESCE(p_patch->>'neurological', neurological),
    acetic_acid_test = COALESCE(p_patch->>'acetic_acid_test', acetic_acid_test),
    acetic_clock_position = COALESCE(p_patch->>'acetic_clock_position', acetic_clock_position),
    acetic_relative_position = COALESCE(p_patch->>'acetic_relative_position', acetic_relative_position),
    lugol_test = COALESCE(p_patch->>'lugol_test', lugol_test),
    lugol_clock_position = COALESCE(p_patch->>'lugol_clock_position', lugol_clock_position),
    lugol_relative_position = COALESCE(p_patch->>'lugol_relative_position', lugol_relative_position),
    gestational_age = COALESCE(p_patch->>'gestational_age', gestational_age),
    fetal_weight = COALESCE((p_patch->>'fetal_weight')::numeric, fetal_weight),
    obstetric_bp = COALESCE(p_patch->>'obstetric_bp', obstetric_bp),
    uterine_height = COALESCE((p_patch->>'uterine_height')::numeric, uterine_height),
    presentation = COALESCE(p_patch->>'presentation', presentation),
    fetal_heart_rate = COALESCE((p_patch->>'fetal_heart_rate')::integer, fetal_heart_rate),
    fetal_movements = COALESCE(p_patch->>'fetal_movements', fetal_movements),
    edema = COALESCE(p_patch->>'edema', edema),
    alarm_signs = COALESCE(p_patch->>'alarm_signs', alarm_signs),
    indications = COALESCE(p_patch->>'indications', indications),
    complementary_exams = COALESCE(p_patch->>'complementary_exams', complementary_exams),
    diagnosis = COALESCE(p_patch->>'diagnosis', diagnosis),
    plan = COALESCE(p_patch->>'plan', plan),
    next_appointment_date = COALESCE((p_patch->>'next_appointment_date')::date, next_appointment_date),
    contact_channel = COALESCE(p_patch->>'contact_channel', contact_channel),
    updated_at = now()
  WHERE id = p_consultation_id
  RETURNING * INTO v_consultation;

  -- Handle consumables if array was provided (not null)
  IF p_consumables IS NOT NULL THEN
    DELETE FROM consultation_consumables WHERE consultation_id = p_consultation_id;
    
    IF jsonb_array_length(p_consumables) > 0 THEN
      FOR v_consumable IN SELECT * FROM jsonb_array_elements(p_consumables)
      LOOP
        INSERT INTO consultation_consumables (consultation_id, item_name, quantity, unit)
        VALUES (
          v_consultation.id,
          v_consumable->>'item_name',
          (v_consumable->>'quantity')::numeric,
          v_consumable->>'unit'
        );
      END LOOP;
    END IF;
  END IF;

  -- Handle next appointment date change
  v_new_next_date := p_patch->>'next_appointment_date';
  IF v_new_next_date IS NOT NULL AND (v_old_next_date IS NULL OR v_new_next_date != v_old_next_date) THEN
    SELECT * INTO v_orig_app FROM appointments WHERE id = v_consultation.appointment_id;
    
    v_scheduled_at := v_new_next_date::date + (v_orig_app.scheduled_at::time);
    IF v_scheduled_at IS NULL THEN
      v_scheduled_at := v_new_next_date::date + time '09:00:00';
    END IF;

    -- Look for an existing upcoming appointment
    SELECT * INTO v_existing_next_app 
    FROM appointments 
    WHERE patient_id = v_consultation.patient_id 
      AND status = 'programada'
      AND scheduled_at > v_orig_app.scheduled_at
    ORDER BY scheduled_at ASC
    LIMIT 1;

    IF FOUND THEN
      UPDATE appointments SET scheduled_at = v_scheduled_at WHERE id = v_existing_next_app.id;
    ELSE
      INSERT INTO appointments (
        patient_id, doctor_id, scheduled_at, status, reason, price, created_by
      ) VALUES (
        v_consultation.patient_id,
        COALESCE(v_orig_app.doctor_id, v_consultation.doctor_id, v_user_id),
        v_scheduled_at,
        'programada',
        'Próxima Cita',
        COALESCE(v_orig_app.price, 0),
        v_user_id
      );
    END IF;
  END IF;

  RETURN to_jsonb(v_consultation);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Migration: 20260709000000_full_schema_dump.sql


